Refactor Tor IP check and update configurations

diff --git a/archnon b/archnon
--- a/archnon
+++ b/archnon
@@ -179,22 +179,16 @@ echo -e "\n- ${LB}resolv: ${GREEN}resolve ${P}.onion ${NC}links${NC}"
 
 myip(){
 
-export agent=( 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36' 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Edg/148.0.3967.83' )
-
 if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1 || pgrep -a tor | grep -IE "tor" >/dev/null 2>&1; then
 
-   echo -e "\n${ORANGE}[${NC}*${ORANGE}]${P} Your Tor IP${NC}:" 
-   curl --socks5-hostname 127.0.0.1:9150 --user-agent "${agent[$RANDOM % ${#agent[@]}]}" https://check.torproject.org/api/ip
+   echo -e "\n${ORANGE}[${NC}*${ORANGE}]${P} From Tor's Network${NC}:${ORANGE}" 
+   curl --socks5-hostname 127.0.0.1:9150 https://check.torproject.org/api/ip
 
-   echo -e "\n${ORANGE}[${NC}*${ORANGE}]${P} Your Tor ISP${NC}:"
-   curl --socks5-hostname 127.0.0.1:9150 'ip-api.com?fields=country,countryCode,as,org,asname,proxy,city,region,regionName,isp,currency'
 else
 
-   echo -e "\n${RED}[${NC}*${RED}]${BLUE} Your Public IP${NC}:" 
-   curl --user-agent "${agent[$RANDOM % ${#agent[@]}]}" https://check.torproject.org/api/ip
+   echo -e "\n${RED}[${NC}*${RED}] Not From Tor ${NC}:${ORANGE}" 
+   curl https://check.torproject.org/api/ip && echo -e "${NC}"
 
-   echo -e "\n${RED}[${NC}*${RED}]${BLUE} Your Public ISP${NC}:" 
-   curl 'ip-api.com?fields=country,countryCode,as,org,asname,proxy,city,region,regionName,isp,currency'
 fi
 
 }
@@ -308,7 +302,7 @@ nft -f /etc/archnon_rules.nft
    if pgrep -a tor | grep -IE "tor" >/dev/null 2>&1 || ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1; then
    echo -e "\n${ORANGE}[${NC}+${ORANGE}]${NC} ArchNoN is running ${BLUE}(${GREEN}done${BLUE})${NC}"
    else
-	 echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Could not start ArchNoN${NC}"
+        echo -e "${RED}[${NC}-${RED}]${NC} Unknown: ${REDCould not start ArchNoN${NC}"
          exit 1
    fi
 }
@@ -336,7 +330,7 @@ ControlPort 127.0.0.1:9151
 EntryNodes {is},{ch},{fi},{ro}
 ExitNodes {is},{ch},{fi},{ro}
 StrictNodes 1
-MaxCircuitDirtiness 20
+MaxCircuitDirtiness 10
 ClientUseIPv6 0
 ClientPreferIPv6ORPORT 0
 ClientRejectInternalAddresses 1
@@ -361,7 +355,7 @@ fi
    elif echo $TOR_USER >/dev/null 2>&1; then
        echo -e "\n${BLUE}[${NC}+${BLUE}]${NC} Tor User: ${P}$TOR_USER${NC}"
    else
-        echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED} Could not find a Tor User${NC}, ${ORANGE}The fix${NC}: ${BLUE}create one manually${NC}"
+        echo -e "\n${RED}[${NC}-${RED}]${NC} Unknown: ${RED}Could not detect a Tor User${NC}, ${ORANGE}The fix${NC}: ${BLUE}create one manually${NC}"
         exit 1
    fi
 	
@@ -404,7 +398,14 @@ if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1 || pgrep -a tor | grep 
    sysctl --system >/dev/null 2>&1
    sudo nft flush ruleset >/dev/null 2>&1
 
-   echo -e "\n${RED}[${NC}*${RED}]${NC} ArchNoN has been ${RED}stopped.${NC}"
+if ! ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1 || ! pgrep -a tor | grep -IE "tor" >/dev/null 2>&1; then
+   echo -e "\n${RED}[${NC}+${RED}]${NC} ArchNoN has been ${RED}stopped.${NC}"
+   exit 0
+else
+   echo -e "${RED}[${NC}-${RED}]${NC} Unknown: ${REDCould not stop ArchNoN${NC}"
+   exit 1
+fi
+
 else
    echo -e "\n${RED}[${NC}-${RED}]${NC} Invalid Argument: ${RED}ArchNoN is not running${NC}"
    exit 1
@@ -474,7 +475,7 @@ if ss -tulpn | grep -iE "6969|9150|9151" >/dev/null 2>&1 || pgrep -a tor | grep 
    
    echo -e "\n${BLUE}[${ORANGE}*${BLUE}]${ORANGE} Requesting a ${P}NEWNYM${NC}..."   
 
-   echo -e "AUTHENTICATE \"\"\nSIGNAL NEWNYM\nQUIT" | nc 127.0.0.1 9151 >/dev/null 2>&1
+   echo -e "AUTHENTICATE \"\"\nSIGNAL NEWNYM\nQUIT" | nc 127.0.0.1 9151 >/dev/null 2>&1 && echo -e "${ORANGE}[${BLUE}*${YELLOW}]${BLUE} You have a new id from Tor${NC}" || echo -e "${RED}[${NC}-${RED}]${NC} Dont be fast, wait ${RED}5 secs${NC} before typing ${ORANGE}'changeid'${NC}"
    
    myip
 
@@ -621,7 +622,7 @@ fi
 
 bridges=$(cat "$file")
 
-echo -e "\n# <--- Generated by ArchNoN ---> #\n# Bridges Configuration #\n# NOT TOUCH, THIS FILE IS CUSTOM LOAD #\n# File locked by chattr +i, unlock: sudo chattr -i /etc/tor/torrc #\nCookieAuthentication 0\nVirtualAddrNetworkIPv4 10.192.0.0/10\nAutomapHostsOnResolve 1\nMaxCircuitDirtiness 20 \nAutomapHostsSuffixes .exit,.onion\nTransPort 127.0.0.1:6969 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr\nDNSPort 127.0.0.1:5353\nControlPort 127.0.0.1:9151\nSocksPort 127.0.0.1:9150 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr\nClientTransportPlugin $kind exec $bin\n$bridges\nUseBridges 1\nClientUseIPv6 0\nClientPreferIPv6ORPORT 0\nClientRejectInternalAddresses 1\nHardwareAccel 1\nEnforceDistinctSubnets 1\nAvoidDiskWrites 1\n" | tee /etc/tor/torrc >/dev/null 2>&1
+echo -e "\n# <--- Generated by ArchNoN ---> #\n# Bridges Configuration #\n# NOT TOUCH, THIS FILE IS CUSTOM LOAD #\n# File locked by chattr +i, unlock: sudo chattr -i /etc/tor/torrc #\nCookieAuthentication 0\nVirtualAddrNetworkIPv4 10.192.0.0/10\nAutomapHostsOnResolve 1\nMaxCircuitDirtiness 10\nAutomapHostsSuffixes .exit,.onion\nTransPort 127.0.0.1:6969 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr\nDNSPort 127.0.0.1:5353\nControlPort 127.0.0.1:9151\nSocksPort 127.0.0.1:9150 IsolateClientAddr IsolateSOCKSAuth IsolateClientProtocol IsolateDestPort IsolateDestAddr\nClientTransportPlugin $kind exec $bin\n$bridges\nUseBridges 1\nClientUseIPv6 0\nClientPreferIPv6ORPORT 0\nClientRejectInternalAddresses 1\nHardwareAccel 1\nEnforceDistinctSubnets 1\nAvoidDiskWrites 1\n" | tee /etc/tor/torrc >/dev/null 2>&1
 
 if tor --verify-config >/dev/null 2>&1; then
    echo -e "\n${P}[${NC}*${P}]${NC} File Touched ${BLUE}(${GREEN}done${BLUE})${NC}"
@@ -665,7 +666,7 @@ ControlPort 127.0.0.1:9151
 EntryNodes {is},{ch},{fi},{ro}
 ExitNodes {is},{ch},{fi},{ro}
 StrictNodes 1
-MaxCircuitDirtiness 20
+MaxCircuitDirtiness 10
 ClientUseIPv6 0
 ClientPreferIPv6ORPORT 0
 ClientRejectInternalAddresses 1
