Update archnon

diff --git a/archnon b/archnon
--- a/archnon
+++ b/archnon
@@ -202,15 +202,18 @@ else
 
    exit 0
 fi
-}                                                    }
 
-start(){                                             
+}
+
+start(){
+
 sudo setenforce 0 >/dev/null 2>&1
 sudo semanage permissive -a unconfined_t >/dev/null 2>&1
 
 modprobe nft_nat >/dev/null 2>&1
 modprobe nft_chain_nat >/dev/null 2>&1
-modprobe nf_nat >/dev/null 2>&1                      
+modprobe nf_nat >/dev/null 2>&1
+
 chattr -i /etc/archnon_rules.nft >/dev/null 2>&1
 
 rm /etc/archnon_rules.nft >/dev/null 2>&1
@@ -228,12 +231,16 @@ table ip6 filter {
         chain FORWARD {
                 type filter hook forward priority filter; policy drop;
         }
-                                                             chain OUTPUT {
-                type filter hook output priority filter; policy drop;                                             }
+
+        chain OUTPUT {
+                type filter hook output priority filter; policy drop;
+        }
 }
-table ip filter {                                            chain INPUT {
+table ip filter {
+        chain INPUT {
                 type filter hook input priority filter; policy drop;
-                iifname "lo" counter packets 16 bytes 1581 accept                                                         ct state related,established counter packets 84 bytes 46784 accept
+                iifname "lo" counter packets 16 bytes 1581 accept
+                ct state related,established counter packets 84 bytes 46784 accept
                 iifname "lo" ip protocol icmp icmp type echo-request ct state related,established counter packets 0 bytes 0 accept
                 ip protocol icmp icmp type echo-request counter packets 0 bytes 0 drop
         }
@@ -261,8 +268,10 @@ table ip nat {
                 ip daddr 127.0.0.1 tcp dport 80 counter packets 0 bytes 0 redirect to :$HTTP
                 ip daddr 127.0.0.1 tcp dport 53 counter packets 0 bytes 0 redirect to :$DNS
                 ip daddr 127.0.0.1 udp dport 53 counter packets 2 bytes 114 redirect to :$DNS
-                skuid $TOR_USER counter packets 2 bytes 120 return                                                        ip daddr 127.0.0.0/8 counter packets 0 bytes 0 return
-                ip daddr 192.168.0.0/16 counter packets 0 bytes 0 return                                                  ip daddr 10.0.0.0/8 counter packets 0 bytes 0 return
+                skuid $TOR_USER counter packets 2 bytes 120 return
+                ip daddr 127.0.0.0/8 counter packets 0 bytes 0 return
+                ip daddr 192.168.0.0/16 counter packets 0 bytes 0 return
+                ip daddr 10.0.0.0/8 counter packets 0 bytes 0 return
                 ip daddr 172.16.0.0/12 counter packets 0 bytes 0 return
                 ip daddr 169.254.0.0/16 counter packets 0 bytes 0 return
                 ip daddr 255.255.255.255 counter packets 0 bytes 0 return
@@ -274,9 +283,12 @@ table ip nat {
 EOT
 
 chattr +i /etc/archnon_rules.nft >/dev/null 2>&1
-                                                     nft -f /etc/archnon_rules.nft >/dev/null 2>&1 && ech -e "\n${BLUE}[${GREEN}+${BLUE}]${GREEN} Firewall Applied !${NC}" || echo -e "\n${RED}[${NC}-${RED}] ${NC}unknown: ${RED}Could not apply Firewall${NC}"
 
-sleep 1                                                                                                      sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null 2>&1
+nft -f /etc/archnon_rules.nft >/dev/null 2>&1 && ech -e "\n${BLUE}[${GREEN}+${BLUE}]${GREEN} Firewall Applied !${NC}" || echo -e "\n${RED}[${NC}-${RED}] ${NC}unknown: ${RED}Could not apply Firewall${NC}"
+
+sleep 1
+
+   sysctl -w net.ipv6.conf.all.disable_ipv6=1 >/dev/null 2>&1
    sysctl -w net.ipv4.icmp_echo_ignore_all=1 >/dev/null 2>&1
    sysctl -w net.ipv6.icmp.echo_ignore_all=1 >/dev/null 2>&1
    sysctl -w net.ipv6.conf.lo.disable_ipv6=1 >/dev/null 2>&1
@@ -287,9 +299,11 @@ sleep 1                                                                         
    pkill -9 tor >/dev/null 2>&1
    pkill -9 NetworkManager >/dev/null 2>&1
 
-   chattr -i /etc/resolv.conf >/dev/null 2>&1        
+   chattr -i /etc/resolv.conf >/dev/null 2>&1
+
    rm /etc/resolv.conf >/dev/null 2>&1
-   touch /etc/resolv.conf >/dev/null 2>&1            
+   touch /etc/resolv.conf >/dev/null 2>&1
+
    echo -e "# Generated By Archnon #\nnameserver 127.0.0.1" | tee /etc/resolv.conf >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}+${BLUE}]${GREEN} DNS Points to ${ORANGE}127${GREEN}.${ORANGE}0${GREEN}.${ORANGE}0${GREEN}.${ORANGE}1${GREEN} !${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not change DNS resolv.conf${NC}"
 
    sleep 1
@@ -301,7 +315,8 @@ sleep 1                                                                         
       NetworkManager >/dev/null 2>&1 && break || continue
    done && echo -e "\n${BLUE}[${GREEN}+${BLUE}]${GREEN} Networking Fixed !${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not fix Networking..${NC}"
 
-   sleep 1                                           
+   sleep 1
+
    tor --User $TOR_USER --RunAsDaemon 1 --DataDirectory /var/lib/tor -f /etc/tor/torrc >/dev/null 2>&1 && echo -e "\n${BLUE}[${GREEN}+${BLUE}]${GREEN} Tor Launched !${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not launch Tor..${NC}"
 
    sleep 1
@@ -315,10 +330,14 @@ sleep 1                                                                         
    else
         sleep 1
 
-        echo -e "\n"                                         echo -e "${RED}[${NC}-${RED}]${NC} unknown: ${RED}could not start Archnon${NC}"
-        exit 1                                          fi
+        echo -e "\n"
+        echo -e "${RED}[${NC}-${RED}]${NC} unknown: ${RED}could not start Archnon${NC}"
+        exit 1
+   fi
 }
-                                                                                                          config(){
+
+
+config(){
 
 if ! cat /etc/tor/torrc | grep -IE "NOT TOUCH, THIS FILE IS CUSTOM LOAD" >/dev/null 2>&1; then
 
@@ -354,53 +373,79 @@ EnforceDistinctSubnets 1
 HardwareAccel 1
 
 EOT
-                                                     chattr +i /etc/tor/torrc >/dev/null 2>&1
-sleep 1                                              
+
+chattr +i /etc/tor/torrc >/dev/null 2>&1
+sleep 1
+
 fi
 
    if id debian-tor >/dev/null 2>&1; then
-       export TOR_USER="debian-tor"                         echo -e "\n${BLUE}[${GREEN}+${BLUE}]${GREEN} Tor User: ${P}$TOR_USER${NC}"
+       export TOR_USER="debian-tor"
+       echo -e "\n${BLUE}[${GREEN}+${BLUE}]${GREEN} Tor User: ${P}$TOR_USER${NC}"
 
    elif id tor >/dev/null 2>&1; then
-       export TOR_USER="tor"                                echo -e "\n${BLUE}[${GREEN}+${BLUE}]${GREEN} Tor User: ${P}$TOR_USER${NC}"
+       export TOR_USER="tor"
+       echo -e "\n${BLUE}[${GREEN}+${BLUE}]${GREEN} Tor User: ${P}$TOR_USER${NC}"
 
    elif id toranon >/dev/null 2>&1; then
        export TOR_USER="toranon"
        echo -e "\n${BLUE}[${GREEN}+${BLUE}]${GREEN} Tor User: ${P}$TOR_USER${NC}"
-                                                        else
+
+   else
         echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not detect a Tor User${NC}"
-        exit 1                                          fi                                                
+        exit 1
+   fi
+
    chown -R $TOR_USER:$TOR_USER /etc/tor/torrc >/dev/null 2>&1
    chown -R $TOR_USER:$TOR_USER /var/lib/tor >/dev/null 2>&1
    chmod 700 /var/lib/tor >/dev/null 2>&1
-   chattr +i /etc/tor/torrc >/dev/null 2>&1          
-   sleep 1                                           
-   start                                             }
-                                                     daemon(){                                            
-   export DPATH=/usr/bin/archdaemon                  
-   if ! command -v archdaemon >/dev/null 2>&1; then             echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Daemon not found, ${ORANGE}(${BLUE}It should be part of your PATH${P}(${LB}$PATH${P})${ORANGE})${NC}"                                                         exit 1
-   fi                                                
+   chattr +i /etc/tor/torrc >/dev/null 2>&1
+
+   sleep 1
+
+   start
+}
+
+daemon(){
+
+   export DPATH=/usr/bin/archdaemon
+
+   if ! command -v archdaemon >/dev/null 2>&1; then
+           echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Daemon not found, ${ORANGE}(${BLUE}It should be part of your PATH${P}(${LB}$PATH${P})${ORANGE})${NC}"
+         exit 1
+   fi
+
    if ! pgrep -a archdaemon >/dev/null 2>&1; then
         archdaemon >/dev/null 2>&1 && echo -e "\n${ORANGE}[${BLUE}+${ORANGE}]${GREEN} Daemon Launched !${NC}\n${ORANGE}[${BLUE}*${ORANGE}]${LB} Note: to stop it just type: ${RED}sudo pkill -9 archdaemon${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not launch daemon script${NC}"
         exit 0
    else
         echo -e "\n${ORANGE}[${BLUE}*${ORANGE}]${GREEN} ArchDaemon is Running, ${LB}your system ensures no leak${NC}"
-        echo -e "\n${ORANGE}[${BLUE}+${ORANGE}]${LB} PID: ${ORANGE}" && pgrep -a archdaemon && echo -e "${NC}"                                                         echo -e "${ORANGE}[${BLUE}*${ORANGE}]${YELLOW} Note: ${LB}to stop it just type: ${RED}sudo pkill -9 archdaemon${NC}"
-        exit 0                                          fi
-}                                                    
-function stop(){                                     
+        echo -e "\n${ORANGE}[${BLUE}+${ORANGE}]${LB} PID: ${ORANGE}" && pgrep -a archdaemon && echo -e "${NC}"
+        echo -e "${ORANGE}[${BLUE}*${ORANGE}]${YELLOW} Note: ${LB}to stop it just type: ${RED}sudo pkill -9 archdaemon${NC}"
+        exit 0
+   fi
+}
+
+function stop(){
+
 if curl --socks5-hostname 127.0.0.1:$SOCKS ifconfig.co >/dev/null 2>&1; then
-                                                        pkill -9 tor >/dev/null 2>&1
-   pkill -9 NetworkManager >/dev/null 2>&1           
-   chattr -i /etc/resolv.conf >/dev/null 2>&1           rm /etc/resolv.conf >/dev/null 2>&1
-   touch /etc/resolv.conf >/dev/null 2>&1            
+
+   pkill -9 tor >/dev/null 2>&1
+   pkill -9 NetworkManager >/dev/null 2>&1
+
+   chattr -i /etc/resolv.conf >/dev/null 2>&1
+   rm /etc/resolv.conf >/dev/null 2>&1
+   touch /etc/resolv.conf >/dev/null 2>&1
+
    echo nameserver 9.9.9.9 | sudo tee /etc/resolv.conf >/dev/null 2>&1
-                                                        chattr +i /etc/resolv.conf >/dev/null 2>&1
+
+   chattr +i /etc/resolv.conf >/dev/null 2>&1
 
    while ! pgrep -a NetworkManager >/dev/null 2>&1; do
         NetworkManager >/dev/null 2>&1 && break || continue
 done
-                                                        sysctl -w net.ipv6.conf.all.disable_ipv6=0 >/dev/null 2>&1
+
+   sysctl -w net.ipv6.conf.all.disable_ipv6=0 >/dev/null 2>&1
    sysctl -w net.ipv4.icmp_echo_ignore_all=0 >/dev/null 2>&1
    sysctl -w net.ipv6.icmp.echo_ignore_all=0 >/dev/null 2>&1
    sysctl -w net.ipv6.conf.lo.disable_ipv6=0 >/dev/null 2>&1
@@ -468,15 +513,19 @@ mode=2
 if [ $EUID -ne 0 ]; then
         echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
         exit 1
-fi                                                   
+fi
+
 if pgrep -a archdaemon >/dev/null 2>&1; then
-    echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${ORANGE}Archdaemon is running${NC}, ${RED}kill it as root before trying to stop${NC}"                         echo -e "\n${RED}[${NC}-${RED}]${YELLOW} Just run: ${P}sudo pkill -9 archdaemon && archnon stop${NC}"
+    echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${ORANGE}Archdaemon is running${NC}, ${RED}kill it as root before trying to stop${NC}"
+    echo -e "\n${RED}[${NC}-${RED}]${YELLOW} Just run: ${P}sudo pkill -9 archdaemon && archnon stop${NC}"
     exit 1
-fi                                                   
+fi
+
 stop
 
 shift
-                                                     break
+
+break
 
 ;;
 
@@ -613,7 +662,8 @@ if [ -f /etc/init.d/archnon ] && command -v rc-service  >/dev/null 2>&1; then
       if ! rc-update | grep -iE "archnon" >/dev/null 2>&1; then
            echo -e "\n${P}[${NC}*${P}]${NC} Archnon is already disabled${NC}"
            exit 0
-      else                                           
+      else
+
       rc-update del archnon default >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}*${ORANGE}]${NC} Archnon has been disable${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not disable Archnon${NC}"
       exit 0
       fi
@@ -659,11 +709,14 @@ break
 
 --help|-help|help)
 mode=9
-                                                     help
 
-shift                                                break
+help
 
-;;                                                   
+shift
+break
+
+;;
+
 --*|-*|*)
 mode=10
 
