Update mactool

diff --git a/mactool b/mactool
--- a/mactool
+++ b/mactool
@@ -20,7 +20,7 @@ NC="\e[0m"
 
 
 if ! (command -v macchanger >/dev/null 2>&1 && command -v figlet >/dev/null 2>&1); then
-       
+
        pkgs=(macchanger figlet)
 
        if [[ $(command -v apt) ]]; then
@@ -55,7 +55,7 @@ if ! (command -v macchanger >/dev/null 2>&1 && command -v figlet >/dev/null 2>&1
                 fi
         elif [[ $(command -v apk) ]]; then
                 if ! apk add --no-cache ${pkgs[@]}; then
-                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}'${pkgs[@]}'${NC}"                
+                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}'${pkgs[@]}'${NC}"
                 exit 1
                 fi
         elif [[ $(command -v emerge) ]]; then
@@ -72,19 +72,18 @@ fi
 # Banner
 
 echo -e "${GREEN}" && figlet MacTool
-echo -n -e "${BLUE}v1.0.0.2"
+echo -n -e "${BLUE}v1.0.0.2 ${LB}-->${GREEN} Archnon's layer 1 anonymation util"
 echo -e "\n"
 echo -e "${ORANGE}[${BLUE}*${ORANGE}] ${YELLOW}Developed By: ${ORANGE}newmasterone27@gmail.com ${NC}"
 
 usage(){
-echo -e "\n${ORANGE}[${YELLOW}!${ORANGE}]${LB} usage: ${P}sudo mactool ${NC}<${LB}option${NC}>${NC}"
-echo -e "\n${BLUE}[${ORANGE}1${BLUE}]${ORANGE} change${BLUE}|${ORANGE}--device${BLUE}|${ORANGE}-d${NC}: ${GREEN}Change MAC Addr of a single device${NC}"
-echo -e "\n${BLUE}[${ORANGE}2${BLUE}]${ORANGE} --enable${BLUE}|${ORANGE}enable${NC}: ${GREEN}Enable ${LB}MAC changing on boot, ${P}usage: ${BLUE}sudo mactool enable ${NC}<${LB}device${NC}>"
-echo -e "\n${BLUE}[${ORANGE}3${BLUE}]${ORANGE} --disable${BLUE}|${ORANGE}disable${NC}: ${RED}Disable ${LB}MAC changing on boot${NC}"
-echo -e "\n${BLUE}[${ORANGE}4${BLUE}]${ORANGE} --daemon${BLUE}|${ORANGE}daemon${NC}: ${BLUE}Daemonize MAC changing by giving an interval, ${BLUE}usage: ${P}sudo mactool ${BLUE}--daemon ${NC}<${LB}device${NC}> ${NC}<${LB}secs${NC}>${NC}"
-echo -e "\n${BLUE}[${ORANGE}5${BLUE}]${ORANGE} restore${BLUE}|${ORANGE}--reset${BLUE}|${ORANGE}reset${NC}: ${YELLOW}Reset Device's MAC Addr to permanent default${NC}"
-echo -e "\n${BLUE}[${ORANGE}6${BLUE}]${ORANGE} --show-devices${BLUE}|${ORANGE}show${NC}: ${LB}Show Available Devices${NC}"
-echo -e "\n${ORANGE}[${BLUE}*${ORANGE}]${RED} Use in case of emergency, it kills your internet connection !!${NC}"
+echo -e "\n${ORANGE}[${YELLOW}*${ORANGE}]${GREEN} usage: ${P}sudo mactool ${NC}<${GREEN}option${NC}>${NC}"
+echo -e "\n${BLUE}[${ORANGE}1${BLUE}] ${ORANGE}change${NC}: ${NC}${GREEN}Change MAC Addr of device${NC}"
+echo -e "\n${BLUE}[${ORANGE}2${BLUE}] ${ORANGE}enable${NC}: ${GREEN}Enable MAC changing on boot${NC}"
+echo -e "\n${BLUE}[${ORANGE}3${BLUE}] ${ORANGE}disable${NC}: ${RED}Disable ${GREEN}MAC changing on boot${NC}"
+echo -e "\n${BLUE}[${ORANGE}4${BLUE}] ${ORANGE}daemon${NC}: ${GREEN}Daemonize MAC changing of device${NC}"
+echo -e "\n${BLUE}[${ORANGE}5${BLUE}] ${ORANGE}restore: ${GREEN}Restore Device's MAC${NC}"
+echo -e "\n${BLUE}[${ORANGE}6${BLUE}] ${ORANGE}show${NC}: ${GREEN}Show Available Devices${NC}"
 }
 
 change(){
@@ -107,22 +106,22 @@ createsv(){
 if [ ! -f /etc/systemd/system/mactool.service ] && command -v systemctl >/dev/null 2>&1; then
     touch /etc/systemd/system/mactool.service
 
-echo -e "\n[Unit]\nDescription=MacTool Service\n[Service]\nType=forking\nExecStart=mactool -d $device\nRemainAfterExit=yes\nUser=root\n[Install]\nWantedBy=multi-user.target" >> /etc/systemd/system/mactool.service
+echo -e "\n[Unit]\nDescription=MacTool Service\n[Service]\nType=forking\nExecStart=mactool change $device\nRemainAfterExit=yes\nUser=root\n[Install]\nWantedBy=multi-user.target" >> /etc/systemd/system/mactool.service
 
 fi
 
 if [ ! -f /etc/sv/mactool/run ] && command -v runit >/dev/null 2>&1; then
     mkdir -p /etc/sv/mactool/
     touch /etc/sv/mactool/run
- 
-    echo -e "#!/bin/sh\nexec mactool -d $device" >> /etc/sv/mactool/run
+
+    echo -e "#!/bin/sh\nexec mactool change $device" >> /etc/sv/mactool/run
     chmod +x /etc/sv/mactool/run
 fi
 
 if [ ! -f /etc/init.d/mactool ] && command -v rc-service >/dev/null 2>&1; then
     touch /etc/init.d/mactool
 
-echo "#!/sbin/openrc-run\nname=MacTool service\ncommand="mactool"\ncommand_args="-d $device"\ncommand_background=true\npidfile="/run/${RC_SVCNAME}.pid"\ndepend() {\n   need net\n}" >> /etc/init.d/mactool
+echo "#!/sbin/openrc-run\nname=MacTool service\ncommand="mactool"\ncommand_args="change $device"\ncommand_background=true\npidfile="/run/${RC_SVCNAME}.pid"\ndepend() {\n   need net\n}" >> /etc/init.d/mactool
 
    chmod +x /etc/init.d/mactool >/dev/null 2>&1
 fi
@@ -141,13 +140,13 @@ fi
 
 if [ -f /etc/sv/mactool/run ] && command -v runit >/dev/null 2>&1; then
 
-	if [ -d /run/runit/service ]; then
-	    RSDIR=/run/runit/service
-	elif [ -d /etc/service ]; then
-	      RSDIR=/etc/service
-	elif [ -d /var/run/service ]; then
-	      RSDIR=/var/run/service
-	fi
+        if [ -d /run/runit/service ]; then
+            RSDIR=/run/runit/service
+        elif [ -d /etc/service ]; then
+              RSDIR=/etc/service
+        elif [ -d /var/run/service ]; then
+              RSDIR=/var/run/service
+        fi
 
       if ls -l $RSDIR/mactool/ >/dev/null 2>&1; then
             echo -e "\n${P}[${NC}*${P}]${NC} MacTool is enabled${NC}"
@@ -182,13 +181,13 @@ fi
 if [ -f /etc/sv/mactool/run ] && command -v runit  >/dev/null 2>&1; then
 
       if [ -d /run/runit/service ]; then
-	  RSDIR=/run/runit/service
+          RSDIR=/run/runit/service
 
       elif [ -d /etc/service ]; then
-	      RSDIR=/etc/service
-	
+              RSDIR=/etc/service
+
       elif [ -d /var/run/service ]; then
-	      RSDIR=/var/run/service
+              RSDIR=/var/run/service
       fi
 
       if ! ls -l $RSDIR/mactool/ >/dev/null 2>&1; then
@@ -215,194 +214,194 @@ fi
 }
 
 dlist(){
-echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${GREEN} Daemon List By PID${LB}(${GREEN}active${BLUE})${NC}: ${ORANGE}"
+echo -e "\n${BLUE}[${GREEN}*${BLUE}]${GREEN} Daemon's Active PDIs${NC}: ${ORANGE}"
 pgrep -a mactd && echo -e "${NC}"
 echo -e "\n${RED}[${NC}-${RED}]${NC} Kill them by running: ${RED}sudo pkill -9 mactd${NC}"
 }
 
 while [ $# -gt 0 ]; do
-	case $1 in
-	
-	change|--device|-d)
-	mode=1
-	device=$2
-	
-	if [ $EUID -ne 0 ]; then
-	    echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
-	    exit 1
-	fi
-	
-	if [ -z $device ]; then
-	    echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
-	    exit 1
-	fi
+        case $1 in
 
-	if ! ip a | grep "$device" >/dev/null 2>&1; then
-		echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
-		exit 1
-	fi
-	
-	change && echo -e "\n${ORANGE}[${BLUE}*${ORANGE}]${GREEN} $device's MAC was changed${ORANGE}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not change MAC Addr of: ${ORANGE}'$device'${NC}"
-	echo -e "${ORANGE}"
-	macchanger -s $device && echo -e "\n${NC}"
-	exit 1
-
-	shift
-	break
-
-
-	;;
-
-	--enable|enable)
-	mode=2
-	device=$2
-
-	if [ $EUID -ne 0 ]; then
-	    echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
-	    exit 1
-	fi
-	
-	if [ -z $device ]; then
-    		echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
-    		exit 1
-	fi
-
-	if ! ip a | grep "$device" >/dev/null 2>&1; then
-        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
-       	 	exit 1
-	fi
-	
-	createsv
-
-	enable
-
-	exit 0
-
-	shift
-	break
-
-	;;
-
-	--disable|disable)
-	mode=3
-	device=$3
+        change|--device|-d)
+        mode=1
+        device=$2
 
         if [ $EUID -ne 0 ]; then
-    		echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
-    		exit 1
-	fi
+            echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
+            exit 1
+        fi
 
-	createsv 
+        if [ -z $device ]; then
+            echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
+            exit 1
+        fi
 
-	disable
+        if ! ip a | grep "$device" >/dev/null 2>&1; then
+                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
+                exit 1
+        fi
 
-	exit 0
+        change && echo -e "\n${ORANGE}[${BLUE}*${ORANGE}]${GREEN} $device's MAC was changed${ORANGE}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not change MAC Addr of: ${ORANGE}'$device'${NC}"
+        echo -e "${ORANGE}"
+        macchanger -s $device && echo -e "\n${NC}"
+        exit 1
 
-	shift
-	break
-
-	;;
-
-	--daemon|daemon)
-   	mode=4
-	i=$2
-	device=$3
-
-	if [ $EUID -ne 0 ]; then
-        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
-        	exit 1
-	fi
-	
-	if pgrep -a mactd >/dev/null 2>&1; then
-		dlist
-	fi
-
-	if [ -z $i ]; then
-		echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing interval(secs)${NC}"
-		exit 1
-	fi
-
-	if [ -z $device ]; then
-        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
-        	exit 1
-	fi
-
-	if ! ip a | grep "$device" >/dev/null 2>&1; then
-		dlist
-       	 	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
-       		exit 1
-	fi
-
-	if ! command -v mactd >> /dev/null 2>&1; then
-		echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Missing Daemon${BLUE}(${ORANGE}'mactd',${LB} it should be in your PATH: ${YELLOW}$PATH${BLUE})"
-		exit 1
-	else
-		mactd $i $device && echo -e "\n${ORANGE}[${BLUE}+${ORANGE}]${GREEN} New Daemon Launched !${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknon: ${RED}Could not launch daemon${NC}"
-		exit 0
-	fi
-
-	shift
-	break
-
-	;;
-	
-	restore|--reset|reset)
-	mode=5
-	device=$2
-        
-	if [ $EUID -ne 0 ]; then
-        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
-        	exit 1
-	fi
+        shift
+        break
 
 
-	if [ -z $device ]; then
-        	usage
-        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
-        	exit 1
-	fi
+        ;;
+
+        --enable|enable)
+        mode=2
+        device=$2
+
+        if [ $EUID -ne 0 ]; then
+            echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
+            exit 1
+        fi
+
+        if [ -z $device ]; then
+                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
+                exit 1
+        fi
+
+        if ! ip a | grep "$device" >/dev/null 2>&1; then
+                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
+                exit 1
+        fi
+
+        createsv
+
+        enable
+
+        exit 0
+
+        shift
+        break
+
+        ;;
+
+        --disable|disable)
+        mode=3
+        device=$3
+
+        if [ $EUID -ne 0 ]; then
+                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
+                exit 1
+        fi
+
+        createsv
+
+        disable
+
+        exit 0
+
+        shift
+        break
+
+        ;;
+
+        --daemon|daemon)
+        mode=4
+        i=$2
+        device=$3
+
+        if [ $EUID -ne 0 ]; then
+                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
+                exit 1
+        fi
+
+        if pgrep -a mactd >/dev/null 2>&1; then
+                dlist
+        fi
+
+        if [ -z $i ]; then
+                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing interval(secs)${NC}"
+                exit 1
+        fi
+
+        if [ -z $device ]; then
+                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
+                exit 1
+        fi
+
+        if ! ip a | grep "$device" >/dev/null 2>&1; then
+                dlist
+                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
+                exit 1
+        fi
+
+        if ! command -v mactd >> /dev/null 2>&1; then
+                echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Missing Daemon${BLUE}(${ORANGE}'mactd',${LB} it should be in your PATH: ${YELLOW}$PATH${BLUE})"
+                exit 1
+        else
+                mactd $i $device && echo -e "\n${ORANGE}[${BLUE}+${ORANGE}]${GREEN} New Daemon Launched !${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknon: ${RED}Could not launch daemon${NC}"
+                exit 0
+        fi
+
+        shift
+        break
+
+        ;;
+
+        restore|--reset|reset)
+        mode=5
+        device=$2
+
+        if [ $EUID -ne 0 ]; then
+                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
+                exit 1
+        fi
 
 
-	if ! ip a | grep "$device" >/dev/null 2>&1; then
-        	usage
-        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
-        	exit 1
-	fi
+        if [ -z $device ]; then
+                usage
+                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
+                exit 1
+        fi
 
-	restore && echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${GREEN} $device's MAC was restored${ORANGE}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not restore MAC of: ${YELLOW}'$device'${ORANGE}"
-	macchanger -s $device && echo -e "\n${NC}"
-	exit 0
-	
-	shift
-	break
 
-	;;
-	
-	--show-devices|show)
-	mode=6
-	
-	echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${GREEN} Available Devices${NC}:" && ip link || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}could not show devices${NC}"
+        if ! ip a | grep "$device" >/dev/null 2>&1; then
+                usage
+                echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
+                exit 1
+        fi
 
-	exit 0
-	shift
-	break
-	
-	;;
+        restore && echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${GREEN} $device's MAC was restored${ORANGE}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not restore MAC of: ${YELLOW}'$device'${ORANGE}"
+        macchanger -s $device && echo -e "\n${NC}"
+        exit 0
 
-	--*|-*|*)
-	mode=6
+        shift
+        break
 
-	usage
-	exit 1
+        ;;
 
-	shift
-	break
+        --show-devices|show)
+        mode=6
 
-	;;
+        echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${GREEN} Available Devices${NC}:" && ip link || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}could not show devices${NC}"
+
+        exit 0
+        shift
+        break
+
+        ;;
+
+        --*|-*|*)
+        mode=6
+
+        usage
+        exit 1
+
+        shift
+        break
+
+        ;;
 esac
 done
 
 if [ -z $mode ]; then
-	usage
-	exit 1
+        usage
+        exit 1
 fi
